<?php 

// This file is generated by Composer
require_once 'php-github-api/vendor/autoload.php';

$client = new \Github\Client();
$repositories = $client->api('user')->repositories('x-formation');


   $response = json_encode(array('response' => $repositories));                   
                    echo $response;
                    exit;
    