<?php 

// This file is generated by Composer
require_once 'php-github-api/vendor/autoload.php';


    class gitstat {
        
        protected $_client;
        
        private function setClient($client) {
            $this->_client = $client;
        }
        private function getClient() {
            return $this->_client;            
        }

        public function __construct() {
            $client = new \Github\Client(
                new \Github\HttpClient\CachedHttpClient(array('cache_dir' => 'tmp/github-api-cache'))
            );
            $client = new \Github\HttpClient\CachedHttpClient();
            $client->setCache(
                new \Github\HttpClient\Cache\FilesystemCache('tmp/github-api-cache')
            );
            $this->setClient($client);
        }
        
        public function getUser() {
            
            $client = new \Github\Client($this->getClient());

        //    $client->authenticate('Dzerad', $password, \Github\Client::AUTH_HTTP_PASSWORD);    
            
            $post = $_POST;
            
            if(isset($post['user']) && !empty($post['user'])) {
                $postUser = $post['user'];
                $repositories = $client->api('user')->repositories($postUser);
                $user = $client->api('user')->show($postUser);
            } else {
                $repositories = $client->api('user')->repositories('x-formation');
                $user = $client->api('user')->show('x-formation');
            }
            
            $response = json_encode(array('response' => $repositories, 'user' => $user));                   
            echo $response;
            exit;            
        }
        
    }
   
    $listener = new gitstat();
    $listener->getUser();   